services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./sql_runner.db:/app/sql_runner.db
    environment:
      - DATABASE_URL=sql_runner.db
    networks:
      - sql-runner-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - sql-runner-network

networks:
  sql-runner-network:
    driver: bridge
